CONTRIBUTING.md
First pass at updating the CONTRIBUTION guide, heavily inspired by the Sails guide.
=> Put together an early pass at the Contribution guide

package.json
Fixed Linda's url in contributors section of package.json.
=> [package]Fixed Linda's url

README.md
With Tutorials, Videos and Support sub sections
=> Add resources section on README

archetype/config/main.js
Doing so would most likely break Windows support.
=> Do not use path concatenation

test/index.js
Fixes all three warnings eslint currently gives for this project. 😀
=> Fix linter errors

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, appveyor.yml
- create issue and pr template files
- update contributing guidelines
- (misc) updated appveyor config
resolves #128
=> Guideline templates

index.js, lib/errors.js, lib/index.js, lib/trails.js, test/index.js, test/testapp.js
- resolves #111 
- resolves #144
=> remove uncaughtException handlers

README.md
Add youtube video link to README
=> [doc] add youtube video to README

index.js, lib/errors.js, lib/trails.js, test/lib/trailpack.test.js, test/lib/trails.test.js, test/mocha.opts
fix merging environment-specific configs. (in config/env)
- resolves #102
- resolves #147
=> [fix] correctly merge env-specific configs

index.js, lib/errors.js, lib/trails.js, package.json, test/index.js, test/lib/trailpack.test.js, test/lib/trails.test.js, test/mocha.opts
freeze config and process.env
- resolves #150 
- resolves #151
=> freeze config and env

appveyor.yml
Run tests on all trailpacks against latest build of Trails
- resolves #153
=> Ecosystem ci

index.js, lib/trails.js, test/index.js, test/lib/trails.test.js, test/testapp.js
- do not fail on typed array freeze
- detect modules required from trailpacks
- add tests
- resolves #177
=> freeze fixes

archetype/test/mocha.opts, archetype/test/setup.js
Addresses #204. Is complemented by https://github.com/trailsjs/generator-trails/pull/56.
Let me know if this is enough or if you think we should add any other setup/teardown logic.
=> [fix] Ensure tests environment is initialized properly

archetype/package.json
Update dependencies archetype
- related to https://github.com/trailsjs/trails/issues/195
=> Update dependencies archetype

README.md
???
- resolves #???
Swapping out the old logo design with the new logo design.
=> In README, update Trails logo

.codeclimate.yml, index.js, lib/errors.js, test/lib/Core.test.js, test/lib/errors.test.js
Code climate does not support custom eslint config plugins, and so eslint-config-trails has no effect. Disable eslint in code-climate.
=> Code climate disable eslint

index.js, lib/errors.js, test/lib/Core.test.js, test/lib/errors.test.js
Fix error names
Trails error types do not correctly display their names in stack traces.
=> Error names

index.js, lib/errors.js, package.json, test/lib/Core.test.js, test/lib/errors.test.js, test/mocha.opts, test/runkitExample.js
Add Runkit example (will show up here: https://runkit.com/npm/trails)
see also https://discuss.runkit.com/t/customizing-your-npm-packages-page-on-tonic/23
=> Runkit example

archetype/package.json, archetype/test/mocha.opts, lib/motd.js, package.json
also update deps for Trails and archetype
- resolves https://github.com/trailsjs/trails/issues/276 also https://github.com/trailsjs/trails/issues/264
=> Fix archetype tests because wasn't working for fresh trails project

lib/Configuration.js, lib/schemas/config.js, package.json, test/lib/Configuration.test.js, test/lib/errors.test.js
- strict checking on immutable being a boolean
- passes config to validateConfig
- adds scott wyatt to list of contributors.
- finishes lib configuration tests
- exception: non-virtual setters are still being allowed for some
reason.
=> [fix] lib tests

index.js, lib/Configuration.js, package.json, test/integration/app.js, test/integration/testpack.js, test/integration/trailsapp.test.js
Config between app/trailpack is merge in the wrong way. 
No fix yet, just create the right unit test of what we really want. Waiting for @tjwebb feedback on #316 issue
- resolves #316
=> v3 config merge fix

lib/Configuration.js, package.json
miss that assign doesn't do deep assignment so this is the fix
=> fix merge deep config and bump to 3.2.1
